Close kituoni referral
Digital-Square-Tanzania/opensrp-client-addo pull request #44
Opened 2024-06-20 11:59 UTC by maulidkategile

Close #34

2024-06-25 13:53 UTC, gosso22 commented on app/src/main/java/org/smartregister/addo/util/ReferralUtils.java
> +        return !AddoApplication.getInstance().getTaskRepository().getTasksByEntityAndCode(planId, groupId, forEntity, requesterName(), code).isEmpty();
@maulidkategile - The method signature here has changed, did you change this in the library? Where are the changes? Also, can you probably find another way of doing this? I am anticipating that changing this method signature might require changing other places where this method is being used

2024-06-25 13:53 UTC, gosso22 requested changes
@maulidkategile - I left you a comment

2024-06-26 09:35 UTC, maulidkategile commented on app/src/main/java/org/smartregister/addo/util/ReferralUtils.java
> +        return !AddoApplication.getInstance().getTaskRepository().getTasksByEntityAndCode(planId, groupId, forEntity, requesterName(), code).isEmpty();
@gosso22 I previously changed the method getTasksByEntityAndCode from opensrp-client-core. Yes, you are right. Instead of changing the existing method, it is better to create a new one to achieve the objective of getting referrals based on the creator. This will help avoid introducing new bugs. 

[Here is the reference for the changes in the opensrp-client-core library](https://github.com/d-tree-org/opensrp-client-core/pull/10)

2024-06-26 09:47 UTC, maulidkategile commented on app/src/main/java/org/smartregister/addo/util/ReferralUtils.java
> +        return !AddoApplication.getInstance().getTaskRepository().getTasksByEntityAndCode(planId, groupId, forEntity, requesterName(), code).isEmpty();
@gosso22 Also, this PR corresponds to this [PR](https://github.com/Digital-Square-Tanzania/opensrp-client-chw-hf/pull/53)

2024-06-28 06:03 UTC, gosso22 approved these changes
LGTM!

2024-07-02 11:23 UTC, gosso22 approved these changes

2024-07-02 12:46 UTC, merged